// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import { AuctionResults } from "local-draw-auction/interfaces/IAuction.sol";
import { IDrawManager } from "local-draw-auction/interfaces/IDrawManager.sol";

contract MockDrawManager is IDrawManager {
  event MockDrawManagerCloseDraw(uint256 randomNumber, AuctionResults[] results);

  /* ============ External Functions ============ */

  /**
   * @notice Called to close a draw and award the completers of each auction.
   * @param _randomNumber Random number generated by the RNG service
   * @param _auctionResults Array of auction results
   * @dev This function can only be called by the manager address.
   */
  function closeDraw(uint256 _randomNumber, AuctionResults[] memory _auctionResults) external {
    emit MockDrawManagerCloseDraw(_randomNumber, _auctionResults);
  }
}
