// SPDX-License-Identifier: GPL-3.0
pragma solidity 0.8.17;

import { Phase } from "src/abstract/PhaseManager.sol";

/// @notice Thrown when the caller is not the PhaseManager contract.
error OnlyPhaseManager();

/**
 * @title PoolTogether V5 DrawAuction
 * @author PoolTogether Inc. Team
 * @notice The DrawAuction uses an auction mechanism to incentivize the completion of the Draw.
 *         This mechanism relies on a linear interpolation to incentivizes anyone to start and complete the Draw.
 *         The first user to complete the Draw gets rewarded with the partial or full PrizePool reserve amount.
 */
interface IDrawAuction {

  /**
   * @notice Called to complete an auction
   * @param _auctionPhases Array of auction phases
   * @param _randomNumber Random number generated by the RNG service
   */
  function completeAuction(
    Phase[] memory _auctionPhases,
    uint256 _randomNumber
  ) external;
}
